<div class="page-margin">
	<div class="container">
		<div class="wow_content">
			<div class="row">
				<div class="col-lg-5">
					<h2 class="tag_contact_sub"><?php echo $wo['lang']['contact_us']; ?></h2>
					<h2 class="tag_contact_title"><?php echo $wo['lang']['contact_help']; ?></h2>
					<span style="display:block; text-align:center;background:#9013ab91;padding: 20px;border-radius: 25px;"><svg xmlns="http://www.w3.org/2000/svg" width="256" height="256" viewBox="0 0 85.551 85.568">
                       <g id="chat-box" transform="translate(-.05)">
                       <path id="Caminho_62" fill="#fff" d="M46.883 32.954c8.182 0 16.133-6.285 16.133-16.821A16.151 16.151 0 0 0 46.883 0h-30.7C7.945 0 .05 6.334.05 16.821A16.159 16.159 0 0 0 13.676 32.76v10.721a2.509 2.509 0 0 0 4.379 1.666l10.862-12.193zm-.067-19.582a3.105 3.105 0 1 1-3.105 3.105 3.106 3.106 0 0 1 3.106-3.105zm-30.569 6.21a3.105 3.105 0 1 1 3.107-3.105 3.105 3.105 0 0 1-3.106 3.105zm15.285-6.21a3.105 3.105 0 1 1-3.105 3.105 3.105 3.105 0 0 1 3.106-3.105z" data-name="Caminho 62"/>
                       <path id="Caminho_63" fill="#f5245f" d="M182.023 236.83h-30.7a16.153 16.153 0 0 0-16.133 16.134c0 10.391 7.818 16.821 16.133 16.821h17.966l10.863 12.193a2.51 2.51 0 0 0 4.379-1.668v-10.72a16.159 16.159 0 0 0 13.626-15.939c0-10.368-7.8-16.821-16.133-16.821zm-30.634 19.584a3.106 3.106 0 1 1 3.105-3.107 3.106 3.106 0 0 1-3.105 3.107zm15.284 0a3.106 3.106 0 1 1 3.105-3.107 3.106 3.106 0 0 1-3.105 3.107zm15.285 0a3.106 3.106 0 1 1 3.105-3.107 3.106 3.106 0 0 1-3.105 3.107z" data-name="Caminho 63" transform="translate(-112.555 -197.25)"/>
                        </g>
                     </svg></span>
				</div>
				<div class="col-lg-1"></div>
				<div class="col-lg-6">
					<div class="wow_sett_content tag_contact_form">
						<form class="contact-us-form form-horizontal" method="post">
							<div class="contact-us-alert setting-update-alert"></div>
							<label class="tag_field">
								<input id="first_name" name="first_name" type="text" placeholder=" ">
								<span><?php echo $wo['lang']['first_name']; ?></span>
							</label>
							<label class="tag_field">
								<input id="last_name" name="last_name" type="text" placeholder=" ">
								<span><?php echo $wo['lang']['last_name']; ?></span>
							</label>
							<label class="tag_field">
								<input id="email" name="email" type="email" placeholder=" ">
								<span><?php echo $wo['lang']['email']; ?></span>
							</label>
							<label class="tag_field">
								<textarea name="message" id="message" rows="5" placeholder=" "></textarea>
								<span><?php echo $wo['lang']['message']; ?></span>
							</label>
							<?php if ($wo['config']['reCaptcha'] == 1 && !empty($wo['config']['reCaptchaKey'])) { ?>
								<div class="wow_form_fields">
									<div id="g-recaptcha-widget"></div>
								</div>
							<?php } ?>
							<div class="round-check">
								<input type="checkbox" name="accept_terms" id="accept_terms" onchange="activateButton(this)">
								<label for="accept_terms"><?php echo str_replace('{privacy}', '<a href="'.Wo_SeoLink('index.php?link1=terms&type=privacy-policy').'">'.$wo['lang']['privacy_policy'].'</a>', $wo['lang']['terms_contact'])  ?></label>
							</div>
							<div class="text-center">
								<button class="btn btn-main btn-mat btn-mat-raised disable_btn" type="submit" name="send" id="send" disabled><?php echo $wo['lang']['send']; ?></button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
<?php if ($wo['config']['reCaptcha'] == 1 && !empty($wo['config']['reCaptchaKey'])) { ?>
	setTimeout(() => {
		widgetId2 = grecaptcha.render(document.getElementById('g-recaptcha-widget'), {
	    'sitekey' : "<?php echo $wo['config']['reCaptchaKey']?>"
	  });
	},500);
<?php } ?>

function activateButton(element) {
	if(element.checked) {
		document.getElementById("send").disabled = false;
	}
	else  {
		document.getElementById("send").disabled = true;
	}
};
   $(function() {
     $('form.contact-us-form').ajaxForm({
       url: Wo_Ajax_Requests_File() + '?f=contact_us',
       beforeSend: function() {
		 $('form.contact-us-form').find('.disable_btn').attr('disabled','disabled');
       },
       success: function(data) {
         if (data.status == 200) {
            $('.contact-us-alert').html('<div class="alert alert-success">' + data.message + '</div>');
            $('.alert-success').fadeIn(300);
         } else {
             var errors = data.errors.join("<br>");
             $('.contact-us-alert').html('<div class="alert alert-danger">' + errors + '</div>');
             $('.alert-danger').fadeIn(300);
         }
		 $('form.contact-us-form').find('.disable_btn').removeAttr("disabled");
       }
     });
   });
</script>