<?php if ($wo['config']['second_post_button'] == 'reaction') { ?>
	<?php if ( isset($wo['story']['viewmode']) && $wo['story']['viewmode'] == 'lightbox') { ?>
		<div class="wo-reaction-lightbox valign stat-item unselectable" data-id="<?php echo $wo['story']['id']; ?>">
			<div class="like-btn like-btn-lightbox unselectable" data-id="<?php echo $wo['story']['id']; ?>" >
				<?php
					if ($wo['loggedin'] && Wo_IsReacted($wo['story']['id'], $wo['user']['user_id']) === true) {
						echo '<div class="valign tag_post_react_btn">';
						echo Wo_GetReactedTextIcon($wo['story']['id'], $wo['user']['user_id']);
						echo '</div>';
					} else {   
						echo '<div class="valign tag_post_react_btn"><span class="status-reaction-'.$wo['story']['id'].' unselectable"><svg xmlns="http://www.w3.org/2000/svg" width="58.553" height="58.266" viewBox="0 0 58.553 58.266"> <path d="M12 21.638h-.014C9.403 21.59 1.95 14.856 1.95 8.478c0-3.064 2.525-5.754 5.403-5.754 2.29 0 3.83 1.58 4.646 2.73.814-1.148 2.354-2.73 4.645-2.73 2.88 0 5.404 2.69 5.404 5.755 0 6.376-7.454 13.11-10.037 13.157H12zM7.354 4.225c-2.08 0-3.903 1.988-3.903 4.255 0 5.74 7.034 11.596 8.55 11.658 1.518-.062 8.55-5.917 8.55-11.658 0-2.267-1.823-4.255-3.903-4.255-2.528 0-3.94 2.936-3.952 2.965-.23.562-1.156.562-1.387 0-.014-.03-1.425-2.965-3.954-2.965z" transform="translate(7126.251 -1222.75)" fill="none" stroke="currentColor" stroke-width="2.5"/> </svg><span class="t_likes'.$wo['story']['id'].'"></span>' . $wo['lang']['like'] . '</span></div>';   
					}    
				?>
			</div>
			<ul class="reactions-box reactions-lightbox-container-<?php echo $wo['story']['id']; ?> unselectable" data-id="<?php echo $wo['story']['id']; ?>">
				<?php if (!empty($wo['reactions_types'])) {
					foreach ($wo['reactions_types'] as $key => $value) {
						if ($value['status'] == 1) {
					 ?>
					<li class="valign reaction reaction-<?php echo $value['id'];?>" data-reaction="<?php echo $value['name'];?>" data-reaction-id="<?php echo $value['id'];?>" data-reaction-lang="<?php echo $value['name'];?>" data-post-id="<?php echo $wo['story']['id']; ?>" onclick="Wo_RegisterReaction(this,'<?php echo($value['wowonder_small_icon']) ?>',<?php echo($value['is_html']) ?>);">
						<?php if (preg_match("/<[^<]+>/",$value['wowonder_icon'],$m)) {
								echo($value['wowonder_icon']);
							 }
							 else{ ?>
							<img src="<?php echo($value['wowonder_icon']) ?>">
						<?php } ?>
					</li>
				<?php } } } ?>
			</ul>
		</div>
	<?php } else { ?>
		<div class="wo-reaction-post valign stat-item unselectable" data-id="<?php echo $wo['story']['id']; ?>">
			<div class="like-btn like-btn-post unselectable"  data-id="<?php echo $wo['story']['id']; ?>" id="react_<?php echo $wo['story']['id']; ?>" <?php if ($wo['loggedin'] && Wo_IsReacted($wo['story']['id'], $wo['user']['user_id'])) { ?> data_react="1" <?php }else{ ?> data_react="0"<?php } ?> data-reaction-id="<?php echo $wo['reactions_types'][1]['id'];?>"  data-reaction="Like" data-reaction-lang="<?php echo $wo['lang']['like'];?>" data-post-id="<?php echo $wo['story']['id']; ?>" onclick="Wo_RegisterReactionLike(this,'<?php echo($wo['reactions_types'][1]['wowonder_small_icon']) ?>',<?php echo($wo['reactions_types'][1]['is_html']) ?>);">
				<?php
					if ($wo['loggedin'] && Wo_IsReacted($wo['story']['id'], $wo['user']['user_id']) === true) { 
						echo '<div class="valign tag_post_react_btn">';
						echo Wo_GetReactedTextIcon($wo['story']['id'], $wo['user']['user_id']);
						echo '</div>';
					} else {   
						echo '<div class="valign tag_post_react_btn"><span class="status-reaction-'.$wo['story']['id'].' unselectable"><svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24"> <path d="M12 21.638h-.014C9.403 21.59 1.95 14.856 1.95 8.478c0-3.064 2.525-5.754 5.403-5.754 2.29 0 3.83 1.58 4.646 2.73.814-1.148 2.354-2.73 4.645-2.73 2.88 0 5.404 2.69 5.404 5.755 0 6.376-7.454 13.11-10.037 13.157H12zM7.354 4.225c-2.08 0-3.903 1.988-3.903 4.255 0 5.74 7.034 11.596 8.55 11.658 1.518-.062 8.55-5.917 8.55-11.658 0-2.267-1.823-4.255-3.903-4.255-2.528 0-3.94 2.936-3.952 2.965-.23.562-1.156.562-1.387 0-.014-.03-1.425-2.965-3.954-2.965z"  fill="currentColor"/> </svg><span class="t_likes'.$wo['story']['id'].'"></span>' . $wo['lang']['like'] . '</span></div>';   
					}    
				?>
			</div>
			<ul class="reactions-box reactions-box-container-<?php echo $wo['story']['id']; ?>" data-id="<?php echo $wo['story']['id']; ?>">
				<?php if (!empty($wo['reactions_types'])) {
					foreach ($wo['reactions_types'] as $key => $value) {
						if ($value['status'] == 1) {
							
					 ?>
					<li class="valign reaction reaction-<?php echo $value['id'];?>" data-reaction="<?php echo $value['name'];?>" data-reaction-id="<?php echo $value['id'];?>" data-reaction-lang="<?php echo $value['name'];?>" data-post-id="<?php echo $wo['story']['id']; ?>" onclick="Wo_RegisterReaction(this,'<?php echo($value['wowonder_small_icon']) ?>',<?php echo($value['is_html']) ?>);">
						<?php if (preg_match("/<[^<]+>/",$value['wowonder_icon'],$m)) {
								echo($value['wowonder_icon']);
							 }
							 else{ ?>
							<img src="<?php echo($value['wowonder_icon']) ?>">
						<?php } ?>
					</li>
				<?php } } } ?>
			</ul>
		</div>
	<?php } ?>
<?php }else{ ?>
	<div <?php echo(PatreonPostSubscribed($wo['story']['user_id'],$wo['story']['id']) ? 'onclick="Wo_RegisterLike('.$wo['story']['id'].');"' : '') ?> id="like-button" class="valign stat-item" title="<?php echo $wo['lang']['like'];?>">
		<?php
			$second_btn_wonder = ($wo['config']['second_post_button'] == 'dislike') ? $wo['lang']['dislike'] : $wo['lang']['wonder'];
			$second_btn_wondered = ($wo['config']['second_post_button'] == 'dislike') ? $wo['lang']['disliked'] : $wo['lang']['wondered'];
			if ($wo['story']['is_liked'] === true) {    
				echo GetModeBtn('liked_btn');  
			} else {
				echo GetModeBtn('like_btn');
			}    
		?>
	</div>
	<?php if ($wo['config']['second_post_button'] != 'disabled') { ?>
		<div <?php echo(PatreonPostSubscribed($wo['story']['user_id'],$wo['story']['id']) ? 'onclick="Wo_RegisterWonder('.$wo['story']['id'].');"' : '') ?> id="wonder-button" class="valign stat-item" title="<?php echo $wo['second_post_button_text'];?>">
			<?php 
				if ($wo['story']['is_wondered'] === true) {  
					echo '<span class="valign active-wonder"><span class="icoo">' . $wo['second_post_button_icon'] . '</span><span class="like-btn-mobile">' . $second_btn_wondered . '</span></span>'; 
				} else {
					echo '<span class="icoo">' . $wo['second_post_button_icon'] . '</span><span class="like-btn-mobile">' . $second_btn_wonder . '</span>';
				}
			?>          
		</div>
	<?php } ?>
<?php } ?>